### ISSUE TITLE
Flux fixes

### ISSUE THREAD

**Issue by JimenaEB** [elianajr/Star-Wars-Blog#6]
No utilizáis este parámetro:
https://github.com/elianajr/Star-Wars-Blog/blob/0df4ccc459809bac4ffaaacb9fb29dc8e8273870/src/js/store/flux.js#L8

Si es una URL debería ser un string:
https://github.com/elianajr/Star-Wars-Blog/blob/0df4ccc459809bac4ffaaacb9fb29dc8e8273870/src/js/store/flux.js#L10

No haría falta guardar la url:
https://github.com/elianajr/Star-Wars-Blog/blob/0df4ccc459809bac4ffaaacb9fb29dc8e8273870/src/js/store/flux.js#L33

Nunca comparamos con undefined:
https://github.com/elianajr/Star-Wars-Blog/blob/0df4ccc459809bac4ffaaacb9fb29dc8e8273870/src/js/store/flux.js#L55

**Comment by elianajr** [comment]
corregido
